### ISSUE TITLE
Reduce heap usage and allocations

### ISSUE THREAD

**Issue by AbstractiveNord** [robotty/twitch-irc-rs#210] opened 2024-03-17 19:50 UTC
Let's use more smart string types, such as FastStr provided via [fast_str crate](https://crates.io/crates/fast-str).

**Comment by Nerixyz** [comment] 2024-03-18 10:30
Seems like a duplicate of #178. As for the type, I think in many cases a `&str` pointing into the raw message can be fine as long as there aren't any escape characters.

**Comment by RAnders00** [comment] 2024-03-18 10:31
Thanks @Nerixyz, I had felt like there was a ticket for that before but must have overlooked it.

**Closed by RAnders00** 2024-03-18 10:31 UTC
Labels: enhancement
